name: Deploy JS Projects on Surge

on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Node Setup
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install Surge
        run: npm i -g surge

      - name: Deploy on Surge
        run: surge ./ cicd-git-act.surge.sh --token ${{secrets.SURGE_TOKEN}}
